.PHONY : ALL
ALL :  core debug e1.10 e1.11 e1.14 e1.16 e1.17 e1.18 e1.19 e1.3 e1.4 e1.7 e1.8 e1.9 fstream t1.1 t1.2 t1.4.1 t1.4.3 vector

core:
	g++ -g -Wall -o core core.cc
debug:
	g++ -g -Wall -o debug debug.cc
e1.10:
	g++ -g -Wall -o e1.10 e1.10.cc
e1.11:
	g++ -g -Wall -o e1.11 e1.11.cc
e1.14:
	g++ -g -Wall -o e1.14 e1.14.cc
e1.16:
	g++ -g -Wall -o e1.16 e1.16.cc
e1.17:
	g++ -g -Wall -o e1.17 e1.17.cc
e1.18:
	g++ -g -Wall -o e1.18 e1.18.cc
e1.19:
	g++ -g -Wall -o e1.19 e1.19.cc
e1.3:
	g++ -g -Wall -o e1.3 e1.3.cc
e1.4:
	g++ -g -Wall -o e1.4 e1.4.cc
e1.7:
	g++ -g -Wall -o e1.7 e1.7.cc
e1.8:
	g++ -g -Wall -o e1.8 e1.8.cc
e1.9:
	g++ -g -Wall -o e1.9 e1.9.cc
fstream:
	g++ -g -Wall -o fstream fstream.cc
t1.1:
	g++ -g -Wall -o t1.1 t1.1.cc
t1.2:
	g++ -g -Wall -o t1.2 t1.2.cc
t1.4.1:
	g++ -g -Wall -o t1.4.1 t1.4.1.cc
t1.4.3:
	g++ -g -Wall -o t1.4.3 t1.4.3.cc
vector:
	g++ -g -Wall -o vector vector.cc

.PHONY : clean
clean : 
	 rm -rf  core debug e1.10 e1.11 e1.14 e1.16 e1.17 e1.18 e1.19 e1.3 e1.4 e1.7 e1.8 e1.9 fstream t1.1 t1.2 t1.4.1 t1.4.3 vector
