.PHONY : ALL
ALL :  core debug fstream t1.1 vector

core:
	g++ -g -o core core.cc
debug:
	g++ -g -o debug debug.cc
fstream:
	g++ -g -o fstream fstream.cc
t1.1:
	g++ -g -o t1.1 t1.1.cc
vector:
	g++ -g -o vector vector.cc

.PHONY : clean
clean : 
	 rm -rf  core debug fstream t1.1 vector
